site_name: The Causal Domain
docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - search.suggest
    - search.highlight

nav:
  - Home: index.md

  - Manuscript:
      - Overview: manuscript/index.md
      - All Pages: manuscript/

  - Glossary:
      - Overview: glossary/index.md
      - All Entries: glossary/

  - Figures:
      - Overview: figures/index.md
      - All Figures: figures/

  - Math:
      - Overview: math/index.md
      - All Math Pages: math/

  - Notes:
      - Overview: notes/index.md
      - All Notes: notes/



markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - awesome-pages


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

