name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Pin MkDocs to avoid MkDocs 2.0
      - run: pip install mkdocs==1.6.1
      - run: pip install mkdocs-material==9.5.17
      - run: pip install mkdocs-awesome-pages-plugin==2.9.2

      - run: mkdocs build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - uses: actions/deploy-pages@v4
